version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: hapi-schema-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hapi
    ports:
      - '5432:5432'
    volumes:
      - ${HOME}/postgres_data:/var/lib/postgresql/data
